### ISSUE TITLE
Enhancement : Making the json converter convert whenever an option is chosen in the dropdown 

### ISSUE THREAD

**Issue by HariKrishna-28** [techrail/devta#115]
### Description
The [JSON converter](https://devta.techrail.in/json-converter) should automatically convert the JSON whenever there is a change in the drop down menu instead of requiring the user to click a convert button.

### Expected behavior
Conversion should be triggered whenever there is a change in the drop down menu.

### Tasks
- [ ]  The drop down menu should be disabled whenever the JSON is invalid. Use [this](https://getbootstrap.com/docs/5.0/forms/select/#disabled) as a reference.
- [ ] Remove the convert button and increase the size of the text area so that both the components (text area and drop down) occupy the full screen. This can be done by tweaking the height of the component with the id `textInput`

**Comment by Siddharth9890** [comment]
hey @HariKrishna-28 i can work on it but can i see the website once before starting. Because the website is giving a error

**Comment by HariKrishna-28** [comment]
@Siddharth9890 The site is down and @vaibhav-kaushal is working on it as we speak. Please clone the repository and run it locally.

**Comment by ansharora28** [comment]
I can work on this if it's not taken up yet

**Comment by shourya102** [comment]
I would like to work on this.
