### ISSUE TITLE
Bug :  Date picker gets cut off in mobile view

### ISSUE THREAD

**Issue by HariKrishna-28** [techrail/devta#118]
### Description

The date picker gets cut off in mobile view for `Date to Unix` and `Time zone converter`.

### Screenshots
![ss1](https://github.com/techrail/devta/assets/69629411/30d910ae-a7cc-4f18-b276-e051ccbba213)
![ss2](https://github.com/techrail/devta/assets/69629411/71c60f3d-b28a-4931-811e-bfb0e0b1a7ce)

### Proposed fix
- Increase the height of the parent container for screens with `max-width: 800px`

**Comment by LordHarsh** [comment]
Hi, can I try working on it?

**Comment by HariKrishna-28** [comment]
Sure! @LordHarsh Please check out the [contributing guide](https://github.com/techrail/devta/blob/main/CONTRIBUTING.md) to get started.
