### ISSUE TITLE
UI fix : Change the output text area of the color picker

### ISSUE THREAD

**Issue by HariKrishna-28** [techrail/devta#126]
## Description

The output text area of the [color picker](https://devta-rust.vercel.app/color-picker-converter) on the right should be refactored with the output component present in `src/components/CopyContainer/SingleLineCopy.vue`

### Current UI
![image](https://github.com/techrail/devta/assets/69629411/2a17ae27-9e75-4461-b7f0-745586b47165)

### Expected UI
![image](https://github.com/techrail/devta/assets/69629411/8de395b1-4e59-42bd-a013-32561def78f2)

**Comment by HariKrishna-28** [comment]
> I would like to work on this issue

@A-Kashif108 Sure! Please check out the [contribution guide](https://github.com/techrail/devta/blob/main/CONTRIBUTING.md) to get started.

**Comment by ansharora28** [comment]
Hey! @A-Kashif108 are you still working on this?

**Comment by Shailendra-Niranjan** [comment]
@HariKrishna-28  hey  can you look  at my Pr.
