### ISSUE TITLE
Create a Base10 to base36

### ISSUE THREAD

**Issue by vaibhav-kaushal** [techrail/devta#128]
We need a converter for changing base 10 numbers to base 36 numbers

**Comment by shourya102** [comment]
I want to work on this.

**Comment by HariKrishna-28** [comment]
@shourya102 Sure!

**Comment by vishalbhowmick** [comment]
![newide](https://github.com/techrail/devta/assets/46847162/84ec10c6-85ca-4b46-857f-627b7ff4056b)
My idea for future is with the number of converters increasing we might need to make something like this, obviously leaving separate pages for the popular or most used while cramming lesser used ones in one page

**Comment by HariKrishna-28** [comment]
@vishalbhowmick Good idea, Can you implement this?

**Comment by vishalbhowmick** [comment]
I am currently working on qr scanner and reader. Meanwhile more converters can be created by others and we can group it later like this
