### ISSUE TITLE
UI Fix

### ISSUE THREAD

**Issue by HariKrishna-28** [techrail/devta#32]
### Description
Components in this application has some UI inconsistencies. Common components like headers, button, input fields, copy text boxes and icon should follow some common styling.

### Proposed Fix
- Make the components follow a common styling or build a custom reusable component that could be reused throughout the application.
- Refactor the headings with appropriate messages.
- Make sure that the text casing, headers and font-family is also consistent throughout components like headers, cards and text-inputs.
- Ensure buttons have appropriate colors based on their role (delete, copy, convert etc).

**Comment by the9esperanto** [comment]
Can I be allowed to resolve the Issue: Inconsistent UI Design in your project titled "DEVTA"? Also, it would be of great help if you describe more changes you want. Please assign.

**Comment by vaibhav-kaushal** [comment]
@the9esperanto There are so many other things to be done. We will list down the issues and then you can pick ones that you like and let us know that you are working on that!
