### ISSUE TITLE
Create a URL Parse for HTTP

### ISSUE THREAD

**Issue by vaibhav-kaushal** [techrail/devta#55]

**Comment by akshays-repo** [comment]
Hi @vaibhav-kaushal ,  could you please explain more about the feature requirement details?

**Comment by theankitbhardwaj** [comment]
Hi @vaibhav-kaushal 
Are you looking for something like this:

https://semalt.tools/en/url-parser?url=https%3A%2F%2Fexample.com%2Fhome.html%3Fname%3DAnkit%26email%3Dab%40gmail.com

**Comment by vaibhav-kaushal** [comment]
> Hi @vaibhav-kaushal Are you looking for something like this:
> 
> https://semalt.tools/en/url-parser?url=https%3A%2F%2Fexample.com%2Fhome.html%3Fname%3DAnkit%26email%3Dab%40gmail.com

Yes. That sounds about right. Thanks for that link. I love the list of tools they have. We can also add some of those tools in our tools list!
